# Generated by Django 3.0.6 on 2020-06-03 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Emp_ID', models.IntegerField()),
                ('First_Name', models.CharField(max_length=50)),
                ('Last_Name', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254)),
                ('Phone', models.CharField(max_length=11)),
                ('Job_Title', models.CharField(max_length=100)),
                ('Department', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=100)),
                ('City', models.CharField(max_length=100)),
                ('Zipcode', models.CharField(max_length=100)),
                ('Country', models.CharField(max_length=100)),
                ('Salary', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
    ]
