# Generated by Django 3.0.6 on 2020-06-03 12:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emp',
            options={'verbose_name_plural': 'Record'},
        ),
        migrations.AddField(
            model_name='emp',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emp',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
